### ISSUE TITLE
Could not resolve module: org.openhab.ui.habot

### ISSUE THREAD

**Issue by sdorra** [ghys/habot#11]
Hi,
I've tried to upgrade habot from 2.3.0-201803221904 to 2.3.0-201804052047, but now i get a bundle exception:

```
org.osgi.framework.BundleException: Could not resolve module: org.openhab.ui.habot [216]
  Unresolved requirement: Import-Package: org.eclipse.jdt.annotation; resolution:="optional"
  Unresolved requirement: Import-Package: org.eclipse.smarthome.automation

	at org.eclipse.osgi.container.Module.start(Module.java:444) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514) [?:?]
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
```

**Comment by ghys** [comment]
Hi Sebastian,
That's right - I added a dependency to the new "experimental" rule engine (
https://docs.openhab.org/configuration/rules-ng.html) to allow push
notifications in the rules created from the chat.
Still have to investigate if that can be made optional... For now you have
to install it from Paper UI, follow the link above.

**Comment by sdorra** [comment]
@ghys thanks, after installing the rules engine everything works as expected.
