### ISSUE TITLE
How to access the local bot?

### ISSUE THREAD

**Issue by SunSeaAndPalms** [ghys/habot#12]
Steps:
- Dropped the *.jar to the addons folder
- Restarted
- No new UI available under `http://pi:8080/start/index`
- 404 if trying to access  `http://pi:8080/habot/index.html`
- Found in logs:
```
21:00:16.061 [ERROR] [org.openhab.ui.habot                 ] - FrameworkEvent ERROR - org.openhab.ui.habot
org.osgi.framework.BundleException: Could not resolve module: org.openhab.ui.habot [260]
  Unresolved requirement: Import-Package: org.eclipse.jdt.annotation; resolution:="optional"
  Unresolved requirement: Import-Package: org.eclipse.smarthome.automation

    at org.eclipse.osgi.container.Module.start(Module.java:444) [?:?]
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1620) [?:?]
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1599) [?:?]
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1571) [?:?]
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1514) [?:?]
    at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [?:?]
    at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
    at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
```

Expected:
- Habot page should pop-up somewhere

**Comment by ghys** [comment]
See #11.

**Comment by SunSeaAndPalms** [comment]
Thank you for hint, I will try this

**Comment by ghys** [comment]
Actually, the very latest version (https://github.com/ghys/habot/releases/tag/2.3.0.201804120154) has the dependency to _org.eclipse.smarthome.automation_ changed to optional, so if you could try that one instead of installing the rule engine to confirm it works, I would be grateful :)

**Comment by SunSeaAndPalms** [comment]
checked the latest version from the provided link works - I see `HABot` in the list of UIs now. Many thanks!
