### ISSUE TITLE
 FrameworkEvent ERROR - org.openhab.ui.habot 

### ISSUE THREAD

**Issue by entnx-01** [ghys/habot#26]
After habot installation the habot doesn´t start. I found the following error in the openhab.log in /var/log/openhab2.

Installed on raspberry pi 3 with openhabian. Openhab Version is 2.3.0-1 (Release Build).

**Error:**
`2018-10-15 10:11:00.565 [ERROR] [org.openhab.ui.habot                ] - FrameworkEvent ERROR - org.openhab.ui.habot
org.osgi.framework.ServiceException: Exception in org.apache.felix.scr.impl.manager.SingleComponentManager.getService()
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:222) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.getService(ServiceFactoryUse.java:111) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceConsumer$2.getService(ServiceConsumer.java:45) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.getService(ServiceRegistrationImpl.java:508) [?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.getService(ServiceRegistry.java:461) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.getService(BundleContextImpl.java:624) [?:?]
        at com.eclipsesource.jaxrs.publisher.internal.ResourceTracker.addingService(ResourceTracker.java:39) [15:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:941) [?:?]
        at org.osgi.util.tracker.ServiceTracker$Tracked.customizerAdding(ServiceTracker.java:870) [?:?]
        at org.osgi.util.tracker.AbstractTracked.trackAdding(AbstractTracked.java:256) [?:?]
        at org.osgi.util.tracker.AbstractTracked.trackInitial(AbstractTracked.java:183) [?:?]
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:318) [?:?]
        at org.osgi.util.tracker.ServiceTracker.open(ServiceTracker.java:261) [?:?]
        at com.eclipsesource.jaxrs.publisher.internal.Activator.openAllServiceTracker(Activator.java:91) [15:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]
        at com.eclipsesource.jaxrs.publisher.internal.Activator.start(Activator.java:55) [15:com.eclipsesource.jaxrs.publisher:5.3.1.201602281253]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:779) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1) [?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:772) [?:?]
        at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:729) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:933) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:309) [?:?]
        at org.eclipse.osgi.container.Module.doStart(Module.java:581) [?:?]
        at org.eclipse.osgi.container.Module.start(Module.java:449) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1634) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1614) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1585) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1528) [?:?]
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230) [?:?]
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340) [?:?]
Caused by: java.lang.NoClassDefFoundError: org/eclipse/smarthome/io/rest/LocaleService
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:?]
        at org.apache.felix.scr.impl.inject.BindMethod.getServiceObjectAssignableMethod(BindMethod.java:459) ~[?:?]
        at org.apache.felix.scr.impl.inject.BindMethod.doFindMethod(BindMethod.java:188) ~[?:?]
        at org.apache.felix.scr.impl.inject.BaseMethod.findMethod(BaseMethod.java:175) ~[?:?]
        at org.apache.felix.scr.impl.inject.BaseMethod.access$400(BaseMethod.java:39) ~[?:?]
        at org.apache.felix.scr.impl.inject.BaseMethod$NotResolved.resolve(BaseMethod.java:593) ~[?:?]
        at org.apache.felix.scr.impl.inject.BaseMethod$NotResolved.methodExists(BaseMethod.java:615) ~[?:?]
        at org.apache.felix.scr.impl.inject.BaseMethod.methodExists(BaseMethod.java:520) ~[?:?]
        at org.apache.felix.scr.impl.inject.BindMethod.getServiceObject(BindMethod.java:648) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2201) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleDynamicCustomizer.prebind(DependencyManager.java:925) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1520) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1006) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:859) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210) ~[?:?]
        ... 30 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.smarthome.io.rest.LocaleService cannot be found by org.openhab.ui.habot_2.4.0.201809260024
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395) ~[?:?]
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387) ~[?:?]
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:?]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:?]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:?]
        at org.apache.felix.scr.impl.inject.BindMethod.getServiceObjectAssignableMethod(BindMethod.java:459) ~[?:?]
        at org.apache.felix.scr.impl.inject.BindMethod.doFindMethod(BindMethod.java:188) ~[?:?]
        at org.apache.felix.scr.impl.inject.BaseMethod.findMethod(BaseMethod.java:175) ~[?:?]
        at org.apache.felix.scr.impl.inject.BaseMethod.access$400(BaseMethod.java:39) ~[?:?]
        at org.apache.felix.scr.impl.inject.BaseMethod$NotResolved.resolve(BaseMethod.java:593) ~[?:?]
        at org.apache.felix.scr.impl.inject.BaseMethod$NotResolved.methodExists(BaseMethod.java:615) ~[?:?]
        at org.apache.felix.scr.impl.inject.BaseMethod.methodExists(BaseMethod.java:520) ~[?:?]
        at org.apache.felix.scr.impl.inject.BindMethod.getServiceObject(BindMethod.java:648) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.getServiceObject(DependencyManager.java:2201) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager$SingleDynamicCustomizer.prebind(DependencyManager.java:925) ~[?:?]
        at org.apache.felix.scr.impl.manager.DependencyManager.prebind(DependencyManager.java:1520) ~[?:?]
        at org.apache.felix.scr.impl.manager.AbstractComponentManager.collectDependencies(AbstractComponentManager.java:1006) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getServiceInternal(SingleComponentManager.java:859) ~[?:?]
        at org.apache.felix.scr.impl.manager.SingleComponentManager.getService(SingleComponentManager.java:823) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse$1.run(ServiceFactoryUse.java:212) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at org.eclipse.osgi.internal.serviceregistry.ServiceFactoryUse.factoryGetService(ServiceFactoryUse.java:210) ~[?:?]
        ... 30 more
`

Do you have any Idea?

**Comment by ghys** [comment]
See #23, don't use the latest releases, use the last one compatible with 2.3.
Also please note that this project will move to the openHAB distribution soon.
